language: R
sudo: false
cache: packages
r_check_args: --as-cran

# devtools + packages for testing
r_packages:
  - dplyr
  - ggvis
  - ggplot2
  - car
  - RColorBrewer
  - rpart
  - pkgdown
  - devtools

install:
  - R -e 'devtools::install(".", dependencies = TRUE)'
  - R -e 'devtools::install_github(c("datacamp/r-completion", "datacamp/r-backend"))'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
